export const browserCoreExamples = [
  "lingshi browser status",
  "lingshi browser start",
  "lingshi browser stop",
  "lingshi browser tabs",
  "lingshi browser open https://example.com",
  "lingshi browser focus abcd1234",
  "lingshi browser close abcd1234",
  "lingshi browser screenshot",
  "lingshi browser screenshot --full-page",
  "lingshi browser screenshot --ref 12",
  "lingshi browser snapshot",
  "lingshi browser snapshot --format aria --limit 200",
  "lingshi browser snapshot --efficient",
  "lingshi browser snapshot --labels",
];

export const browserActionExamples = [
  "lingshi browser navigate https://example.com",
  "lingshi browser resize 1280 720",
  "lingshi browser click 12 --double",
  'lingshi browser type 23 "hello" --submit',
  "lingshi browser press Enter",
  "lingshi browser hover 44",
  "lingshi browser drag 10 11",
  "lingshi browser select 9 OptionA OptionB",
  "lingshi browser upload /tmp/file.pdf",
  'lingshi browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "lingshi browser dialog --accept",
  'lingshi browser wait --text "Done"',
  "lingshi browser evaluate --fn '(el) => el.textContent' --ref 7",
  "lingshi browser console --level error",
  "lingshi browser pdf",
];
